name: Composer CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: Restore yarn cache
        uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/Composer/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn install
        working-directory: Composer
      - name: yarn build:dev
        run: yarn build:dev
        working-directory: Composer
      - name: yarn lint
        run: yarn lint
        working-directory: Composer
      - name: yarn test:coverage
        run: yarn test:coverage
        working-directory: Composer

  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: Restore yarn cache
        uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/Composer/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn install
        working-directory: Composer
      - name: yarn build:prod
        run: yarn build:prod
        working-directory: Composer
      - name: yarn test:integration
        run: yarn test:integration
        working-directory: Composer
        continue-on-error: true
        env:
          CYPRESS_COMPOSER_URL: http://localhost:5000
      - name: Archive E2E Failures
        uses: actions/upload-artifact@v1
        with:
          name: cypress
          path: Composer/cypress/screenshots

  botproject:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Dotnet Version
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.1.802" # SDK Version to use.
      - name: dotnet build
        run: dotnet build
        working-directory: BotProject/CSharp
      - name: dotnet test
        run: dotnet test
        working-directory: BotProject/CSharp
