name: Composer CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: Restore yarn cache
        uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/Composer/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        run: yarn install
        working-directory: Composer
      - name: Build
        run: yarn build:dev
        working-directory: Composer
      - name: Lint
        run: yarn lint
        working-directory: Composer
      - name: Test
        run: yarn test:coverage
        working-directory: Composer

  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: Restore yarn cache
        uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/Composer/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        run: yarn install
        working-directory: Composer
      - name: Build
        run: yarn build:prod
        working-directory: Composer
      - name: E2E Tests
        run: yarn test:integration
        working-directory: Composer
        continue-on-error: true
        env:
          CYPRESS_COMPOSER_URL: http://localhost:5000
      - name: Archive E2E Failures
        uses: actions/upload-artifact@v1
        with:
          name: cypress
          path: Composer/cypress/screenshots

  botproject:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Dotnet Version
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.0.100" # SDK Version to use.
      - run: dotnet --info
      - name: Build BotProject
        run: dotnet build BotProject.csproj
        working-directory: BotProject/CSharp
      - name: Build Tests
        run: dotnet build Tests/Tests.csproj
        working-directory: BotProject/CSharp
      - name: Test
        run: dotnet test Tests/Tests.csproj
        working-directory: BotProject/CSharp
