name: Node CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/Composer/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        run: cd Composer && yarn install
      - name: Yarn Build
        run: cd Composer && yarn build
      - name: Yarn Test
        run: cd Composer && yarn test:coverage
