name: Validate PR

on: [pull_request]

jobs:
  check-stable-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./.github/actions/check-stable-branch
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
